version: '3.7'

services:
  dracula:
    image: dracula:$TAG
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: "top.secret.token"
      NAME: Bacula-Dir
      ADDRESS: Ba.cu.la.dr
      PASSWORD: "Top Secret Password"
    restart: "no"
    command: "true"
